# Generated by Django 4.1.6 on 2023-02-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAccount', models.IntegerField()),
                ('nameUser', models.CharField(max_length=50)),
                ('saldo', models.IntegerField()),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacciones.account'),
        ),
    ]
