# Generated by Django 4.1.6 on 2023-03-07 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_account_transaction_iduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='nameUser',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposito', 'Deposito'), ('Retiro', 'Retiro'), ('Transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAcc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='transacciones.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.ManyToManyField(to='transacciones.contact'),
        ),
    ]
