# Generated by Django 4.1.7 on 2023-03-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('transacciones', '0005_delete_user_account_user_alter_account_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='idAcc',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
