# Generated by Django 4.1.6 on 2023-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposito', 'Deposito'), ('Retiro', 'Retiro')], max_length=10),
        ),
    ]
