# Generated by Django 4.1.7 on 2023-03-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
